[package]
name = "micromux-tui"
version = "0.1.0"
edition.workspace = true

[dependencies]
color-eyre.workspace = true
itertools.workspace = true
indexmap.workspace = true
strum.workspace = true

# tracing
tracing.workspace = true

# micromux
micromux = { path = "../micromux/" }

# tui
ratatui = { version = "0", features = [] }
ansi-to-tui = "7"
strip-ansi-escapes = "0"
crossterm = { version = "0.28.1", features = ["event-stream"] }

# async runtime
tokio.workspace = true
tokio-stream = "0"
futures.workspace = true
