[workspace]
resolver = "2"
members = [
	"crates/micromux",
	"crates/micromux-tui",
	"crates/micromux-cli",
]

[workspace.package]
edition = "2024"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[workspace.dependencies]
color-eyre = "0"
thiserror = "2"
itertools = "0"
rand = "0"
indexmap = "2"
strum = { version = "0", features = ["derive"] }
enum-as-inner = "0"
# derive_more = { version = "2", features = ["from", "into", "display", "debug"] }

# tracing
tracing = "0"

# diagnostics
codespan-reporting = "0"

# serde
serde = { version = "1", features = ["derive"] }
# TODO: remove
# serde_yaml = "0"

# async runtime
tokio = { version = "1", features = ["full"] }
tokio-util = "0"
futures = "0"
