[workspace]
resolver = "2"
members = [
	"crates/micromux-tui",
	"crates/micromux",
]

[workspace.package]
edition = "2024"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[workspace.dependencies]
color-eyre = "0"
itertools = "0"
rand = "0"
strum = { version = "0", features = ["derive"] }

# serde
serde = { version = "1", features = ["derive"] }
serde_yaml = "0"
